name: Deploy to ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECS_SERVICE: queso-service
  ECS_CLUSTER: queso-cluster
  ECS_TASK_DEFINITION: queso-task
  CONTAINER_NAME: queso-container
  PULUMI_SKIP_UPDATE_CHECK: true
  PULUMI_STATE_BUCKET: queso-state

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:$HOME/.pulumi/bin
          pulumi version

      - name: Install dependencies
        run: |
          cd distribution/ecs
          npm install

      - name: Clear Pulumi locks
        run: |
          cd distribution/ecs
          pulumi login s3://${{ env.PULUMI_STATE_BUCKET }}
          # Try to cancel any existing operations
          pulumi cancel --yes || true
          # Force remove lock files if cancel didn't work
          aws s3 rm s3://${{ env.PULUMI_STATE_BUCKET }}/.pulumi/locks/organization/queso/prod/ --recursive || true
          # Wait a moment for S3 consistency
          sleep 5

      - name: Deploy infrastructure
        run: |
          cd distribution/ecs
          pulumi login s3://${{ env.PULUMI_STATE_BUCKET }}
          pulumi stack select prod --create
          pulumi config set aws:region ${{ env.AWS_REGION }}
          pulumi up --yes
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
